package poo.programa1.GUI;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import poo.programa1.Atleta;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dandi
 */
        
        
public class ActualizarAtleta extends javax.swing.JFrame {
    private String pNombre;
    private String pApellido1;
    private String pApellido2;
    private String pPais;
    private LocalDate pFecha;
    private String pCorreo;
    private String pTelefono;

    // método que rellena el ComboBox con las identificaciones de los atletas registrados.
    private void fillComboAtletas(){
        Atleta.List.forEach((key, value) -> {
            if (value instanceof Atleta){
                listaAtletas.addItem(key);
            }
        });
    }    
    /**
     * Creates new form AgregarAtleta
     */
    public ActualizarAtleta(){
        initComponents();
        this.setLocationRelativeTo(null);
        fillComboAtletas();
        listaAtletas.setSelectedItem(null);
        NombreTXT.setText("");
        Apellido1TXT.setText("");
        Apellido2TXT.setText("");
        PaisTXT.setText("");
        FechaTXT.setText("");
        CorreoTXT.setText("");
        TelefonoTXT.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AgregarAtletaTitle = new javax.swing.JLabel();
        Apellido1TXT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        NombreTXT = new javax.swing.JTextField();
        Apellido2TXT = new javax.swing.JTextField();
        PaisTXT = new javax.swing.JTextField();
        FechaTXT = new javax.swing.JTextField();
        CorreoTXT = new javax.swing.JTextField();
        TelefonoTXT = new javax.swing.JTextField();
        AceptarAtletaButton = new javax.swing.JButton();
        CancelarAtletaButton = new javax.swing.JButton();
        listaAtletas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AgregarAtletaTitle.setText("Actualizar atleta");

        Apellido1TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Apellido1TXTActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jLabel3.setText("Primer apellido:");

        jLabel4.setText("Segundo apellido:");

        jLabel5.setText("Identificación:");

        jLabel6.setText("País de origen:");

        jLabel7.setText("Fecha de nacimiento");

        jLabel8.setText("Correo electrónico");

        jLabel9.setText("Teléfono:");

        NombreTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTXTActionPerformed(evt);
            }
        });

        Apellido2TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Apellido2TXTActionPerformed(evt);
            }
        });

        PaisTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaisTXTActionPerformed(evt);
            }
        });

        FechaTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaTXTActionPerformed(evt);
            }
        });

        CorreoTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoTXTActionPerformed(evt);
            }
        });

        TelefonoTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoTXTActionPerformed(evt);
            }
        });

        AceptarAtletaButton.setText("Aceptar");
        AceptarAtletaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarAtletaButtonActionPerformed(evt);
            }
        });

        CancelarAtletaButton.setText("Cancelar");
        CancelarAtletaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarAtletaButtonActionPerformed(evt);
            }
        });

        listaAtletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaAtletasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(39, 39, 39)
                        .addComponent(PaisTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FechaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TelefonoTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(CorreoTXT)))
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Apellido1TXT))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(NombreTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                .addComponent(Apellido2TXT, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(listaAtletas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AceptarAtletaButton)
                    .addComponent(CancelarAtletaButton))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AgregarAtletaTitle)
                .addGap(204, 204, 204))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Apellido1TXT, Apellido2TXT, CorreoTXT, FechaTXT, NombreTXT, PaisTXT, TelefonoTXT});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(AgregarAtletaTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(listaAtletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AceptarAtletaButton)
                        .addGap(34, 34, 34)
                        .addComponent(CancelarAtletaButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(NombreTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Apellido1TXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Apellido2TXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PaisTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FechaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CorreoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TelefonoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarAtletaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarAtletaButtonActionPerformed
        // TODO add your handling code here:
        String id = (String) listaAtletas.getSelectedItem();
        Atleta atleta = (Atleta) Atleta.List.get(id);
        pNombre = NombreTXT.getText();
        System.out.println(pNombre + " "  + pNombre.length());
        if (2 > pNombre.length() || pNombre.length() > 20){
            JOptionPane.showMessageDialog(this, "El nombre debe tener una longitud de 2 a 20 caracteres", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        pApellido1 = Apellido1TXT.getText();
        if (2 > pApellido1.length() || pApellido1.length() > 20){
            JOptionPane.showMessageDialog(this, "El primer apellido debe tener una longitud de 2 a 20 caracteres", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        pApellido2 = Apellido2TXT.getText();
        if (2 > pApellido2.length() || pApellido2.length() > 20){
            JOptionPane.showMessageDialog(this, "El segundo apellido debe tener una longitud de 2 a 20 caracteres", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        pPais = PaisTXT.getText();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        try {
            pFecha = LocalDate.parse(FechaTXT.getText(), formatter);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "El formato de fecha es inválido.", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        pCorreo = CorreoTXT.getText();
        // VALIDAR QUE EXISTA
        
        pTelefono = TelefonoTXT.getText();
        if (pTelefono.length() != 20){
            JOptionPane.showMessageDialog(this, "La identificación debe tener una longitud de 9 a 20 caracteres.", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        atleta.setNombre(pNombre);
        atleta.setApellido1(pApellido1);
        atleta.setApellido2(pApellido2);
        atleta.setCorreo(pCorreo);
        atleta.setFecha(pFecha);
        atleta.setPais(pPais);
        atleta.setTelefono(pTelefono);
        String successMessage = "¡Atleta actualizado con éxito!";
        JOptionPane.showMessageDialog(this, successMessage);
     
    }//GEN-LAST:event_AceptarAtletaButtonActionPerformed

    private void NombreTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTXTActionPerformed
        // TODO add your handling code here:
        pNombre = NombreTXT.getText();
    }//GEN-LAST:event_NombreTXTActionPerformed

    private void Apellido2TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apellido2TXTActionPerformed
        // TODO add your handling code here:
        pApellido2 = Apellido2TXT.getText();
    }//GEN-LAST:event_Apellido2TXTActionPerformed

    private void PaisTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaisTXTActionPerformed
        // TODO add your handling code here:
        pPais = PaisTXT.getText();
    }//GEN-LAST:event_PaisTXTActionPerformed

    
    // ######################################
    private void FechaTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaTXTActionPerformed
        // TODO add your handling code here:
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        pFecha = LocalDate.parse(FechaTXT.getText(), formatter);
    }//GEN-LAST:event_FechaTXTActionPerformed

    private void CorreoTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoTXTActionPerformed
        // TODO add your handling code here:
        pCorreo = CorreoTXT.getText();
    }//GEN-LAST:event_CorreoTXTActionPerformed

    private void TelefonoTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoTXTActionPerformed
        // TODO add your handling code here:
        pTelefono = TelefonoTXT.getText();
    }//GEN-LAST:event_TelefonoTXTActionPerformed

    private void CancelarAtletaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarAtletaButtonActionPerformed
        // TODO add your handling code here:
        //  Close
        dispose();
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
    }//GEN-LAST:event_CancelarAtletaButtonActionPerformed

    private void Apellido1TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apellido1TXTActionPerformed
        // TODO add your handling code here:
        pApellido1 = Apellido1TXT.getText();
    }//GEN-LAST:event_Apellido1TXTActionPerformed

    private void listaAtletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaAtletasActionPerformed
        // TODO add your handling code here:
        String id = (String) listaAtletas.getSelectedItem();
        Atleta atleta = (Atleta) Atleta.List.get(id);
        if (atleta == null){
            return;
        }
        NombreTXT.setText(atleta.getNombre());
        Apellido1TXT.setText(atleta.getApellido1());
        Apellido2TXT.setText(atleta.getApellido2());
        PaisTXT.setText(atleta.getPais());
        FechaTXT.setText(atleta.getFecha().toString());
        CorreoTXT.setText(atleta.getCorreo());
        TelefonoTXT.setText(atleta.getTelefono());
    }//GEN-LAST:event_listaAtletasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarAtleta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarAtletaButton;
    private javax.swing.JLabel AgregarAtletaTitle;
    private javax.swing.JTextField Apellido1TXT;
    private javax.swing.JTextField Apellido2TXT;
    private javax.swing.JButton CancelarAtletaButton;
    private javax.swing.JTextField CorreoTXT;
    private javax.swing.JTextField FechaTXT;
    private javax.swing.JTextField NombreTXT;
    private javax.swing.JTextField PaisTXT;
    private javax.swing.JTextField TelefonoTXT;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> listaAtletas;
    // End of variables declaration//GEN-END:variables
}
