/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo.programa1.GUI;

import javax.swing.JOptionPane;
import poo.programa1.*;

/**
 *
 * @author dandi
 */
public class ActualizarListaAtletas extends javax.swing.JFrame {
      private Visor visor;
      private Atleta atleta;
      /**
       * Creates new form ActualizarListaAtletas
       */
      public ActualizarListaAtletas() {
            initComponents();
            this.setLocationRelativeTo(null);
            FillComboVisores();
            ComboVisores.setSelectedItem(null);
      }
      
      private void FillComboVisores(){
        Atleta.List.forEach((key, value) -> {
            if (value instanceof Visor){
                ComboVisores.addItem(key);
            }
        });
    } 
      
      private void FillComboAtletasVisores(){
            if (visor == null){
                  return;
            }
            ComboAtletasVisores.removeAllItems();
            for (Atleta atleta : visor.getAtletas()){
                  ComboAtletasVisores.addItem(atleta.getId());
            }
      }
      
      private void FillComboAtletasList(){
            if (visor == null){
                  return;
            }
            ComboAtletasList.removeAllItems();
            Atleta.List.forEach((key, value) -> {
                  if (value instanceof Atleta){
                        if(!visor.getAtletas().contains(value)){
                              ComboAtletasList.addItem(key);
                        }
                  }
            });
      }
      
      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            ComboVisores = new javax.swing.JComboBox<>();
            ComboAtletasVisores = new javax.swing.JComboBox<>();
            ComboAtletasList = new javax.swing.JComboBox<>();
            BorrarButton = new javax.swing.JButton();
            CerrarButton = new javax.swing.JButton();
            AgregarButton = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jLabel1.setText("Actualizar listas de visores");

            jLabel2.setText("Visor");

            jLabel3.setText("Atletas en la lista");

            jLabel4.setText("Atletas no en la lista");

            ComboVisores.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        ComboVisoresActionPerformed(evt);
                  }
            });

            BorrarButton.setText("Borrar");
            BorrarButton.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        BorrarButtonActionPerformed(evt);
                  }
            });

            CerrarButton.setText("Cerrar");
            CerrarButton.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        CerrarButtonActionPerformed(evt);
                  }
            });

            AgregarButton.setText("Agregar");
            AgregarButton.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        AgregarButtonActionPerformed(evt);
                  }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                              .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ComboAtletasList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                              .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addGroup(layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jLabel2))
                                          .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel3)))
                                    .addGap(27, 27, 27)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                          .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addComponent(ComboVisores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addComponent(ComboAtletasVisores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                              .addComponent(CerrarButton)
                              .addComponent(BorrarButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(AgregarButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(39, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel2)
                              .addComponent(ComboVisores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(CerrarButton))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(jLabel3)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ComboAtletasVisores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BorrarButton)))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel4)
                              .addComponent(ComboAtletasList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(AgregarButton))
                        .addGap(0, 28, Short.MAX_VALUE))
            );

            pack();
      }// </editor-fold>//GEN-END:initComponents

      private void BorrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarButtonActionPerformed
            // TODO add your handling code here:
            System.out.println(visor.getNombre());
            if (visor == null){
                  return;
            }
            String id = (String) ComboAtletasVisores.getSelectedItem();
            atleta = (Atleta) Persona.List.get(id);
            
            if (atleta == null){
                  System.out.println("hola");
                  return;
            }
            
            int input = JOptionPane.showConfirmDialog(null, "¿Desea borrar?", "Selecione una opción...",
				JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
            // 0=sí, 1=no,
            if (input == 0){
                  visor.borrarAtleta(atleta.getId());
                  JOptionPane.showMessageDialog(this, "Atleta borrado existosamente.");
            }
            FillComboAtletasList();
            FillComboAtletasVisores();
      }//GEN-LAST:event_BorrarButtonActionPerformed

      private void ComboVisoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboVisoresActionPerformed
            // TODO add your handling code here:
            String id = (String) ComboVisores.getSelectedItem();
            visor = (Visor) Persona.List.get(id);
            
            if (visor == null){
                  return;
            }
            FillComboAtletasList();
            FillComboAtletasVisores();
      }//GEN-LAST:event_ComboVisoresActionPerformed

      private void CerrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarButtonActionPerformed
            // TODO add your handling code here:
            dispose();
            MenuPrincipal menu = new MenuPrincipal();
            menu.setVisible(true);
      }//GEN-LAST:event_CerrarButtonActionPerformed

      private void AgregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarButtonActionPerformed
            // TODO add your handling code here:
            if (visor == null){
                  return;
            }
            String id = (String) ComboAtletasList.getSelectedItem();
            atleta = (Atleta) Atleta.List.get(id);
            System.out.println(atleta.getNombre());
            if (atleta == null){
                  return;
            }
            
            visor.agregarAtleta(atleta);
            JOptionPane.showMessageDialog(this, "Atleta agregado a la lista existosamente.");
            
            FillComboAtletasList();
            FillComboAtletasVisores();
            
      }//GEN-LAST:event_AgregarButtonActionPerformed

      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(ActualizarListaAtletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(ActualizarListaAtletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(ActualizarListaAtletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(ActualizarListaAtletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        new ActualizarListaAtletas().setVisible(true);
                  }
            });
      }

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JButton AgregarButton;
      private javax.swing.JButton BorrarButton;
      private javax.swing.JButton CerrarButton;
      private javax.swing.JComboBox<String> ComboAtletasList;
      private javax.swing.JComboBox<String> ComboAtletasVisores;
      private javax.swing.JComboBox<String> ComboVisores;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLabel jLabel3;
      private javax.swing.JLabel jLabel4;
      // End of variables declaration//GEN-END:variables
}
