/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo.programa1.GUI;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;
import poo.programa1.*;

/**
 *
 * @author dandi
 */
public class ActualizarDatosCompetencia extends javax.swing.JFrame {
      private Competencia competencia;
      private String pNombre;
      private String pPais;
      private String pLugar; 
      private LocalDate pFechainicio;
      private LocalDate pFechafinal;     
     
     /**
      * Creates new form ConsultarCompetencia
      */
     public ActualizarDatosCompetencia() {
          initComponents();
          this.setLocationRelativeTo(null);
          FillComboCompetencias();
          ComboCompetencias.setSelectedItem(null);
     }

     private void FillComboCompetencias(){
          for(Map.Entry entry : Competencia.competencias.entrySet()){
               Object Items = entry.getKey();
               ComboCompetencias.addItem((String) Items);
          }
     }
     
     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            jLabel6 = new javax.swing.JLabel();
            jLabel7 = new javax.swing.JLabel();
            jLabel8 = new javax.swing.JLabel();
            ComboCompetencias = new javax.swing.JComboBox<>();
            CerrarButton = new javax.swing.JButton();
            NombreTXT = new javax.swing.JTextField();
            PaisTXT = new javax.swing.JTextField();
            LugarTXT = new javax.swing.JTextField();
            FechainicioTXT = new javax.swing.JTextField();
            FechafinalTXT = new javax.swing.JTextField();
            AceptarButton = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jLabel1.setText("Actualizar Competencia");

            jLabel2.setText("Competencia");

            jLabel3.setText("Nombre");

            jLabel5.setText("País");

            jLabel6.setText("Lugar");

            jLabel7.setText("Fecha de inicio");

            jLabel8.setText("Fecha final");

            ComboCompetencias.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        ComboCompetenciasActionPerformed(evt);
                  }
            });

            CerrarButton.setText("Cancelar");
            CerrarButton.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        CerrarButtonActionPerformed(evt);
                  }
            });

            AceptarButton.setText("Aceptar");
            AceptarButton.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        AceptarButtonActionPerformed(evt);
                  }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                              .addGroup(layout.createSequentialGroup()
                                    .addGap(140, 140, 140)
                                    .addComponent(jLabel1))
                              .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addComponent(jLabel2)
                                          .addComponent(jLabel3)
                                          .addComponent(jLabel6)
                                          .addComponent(jLabel7)
                                          .addComponent(jLabel8)
                                          .addComponent(jLabel5))
                                    .addGap(38, 38, 38)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addComponent(ComboCompetencias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addComponent(NombreTXT)
                                          .addComponent(PaisTXT)
                                          .addComponent(LugarTXT)
                                          .addComponent(FechainicioTXT)
                                          .addComponent(FechafinalTXT))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                              .addComponent(CerrarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                              .addComponent(AceptarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19))
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel2)
                              .addComponent(ComboCompetencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                          .addComponent(jLabel3)
                                          .addComponent(NombreTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                              .addGroup(layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(AceptarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                          .addComponent(CerrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(LugarTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                              .addGroup(layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                          .addComponent(jLabel5)
                                          .addComponent(PaisTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(35, 35, 35)
                                    .addComponent(jLabel6)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel7)
                              .addComponent(FechainicioTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel8)
                              .addComponent(FechafinalTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 7, Short.MAX_VALUE))
            );

            pack();
      }// </editor-fold>//GEN-END:initComponents

     private void CerrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarButtonActionPerformed
          // TODO add your handling code here:
          dispose();
          MenuPrincipal menu = new MenuPrincipal();
          menu.setVisible(true);
     }//GEN-LAST:event_CerrarButtonActionPerformed

     private void ComboCompetenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCompetenciasActionPerformed
          // TODO add your handling code here:
          competencia = Competencia.competencias.get((String)ComboCompetencias.getSelectedItem());
          if (competencia == null){
               return;
          }
          NombreTXT.setText(competencia.getNombre());
          PaisTXT.setText(competencia.getPais());
          LugarTXT.setText(competencia.getLugar());
          FechainicioTXT.setText(competencia.getFechafinal().toString());
          FechafinalTXT.setText(competencia.getFechafinal().toString());  
     }//GEN-LAST:event_ComboCompetenciasActionPerformed

      private void AceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarButtonActionPerformed
            // TODO add your handling code here:
            if (competencia == null){
                  return;
            }
            
          pNombre = NombreTXT.getText();
          pPais = PaisTXT.getText();
          pLugar = LugarTXT.getText();
            if (5 > pNombre.length() || pNombre.length() > 60){
            JOptionPane.showMessageDialog(this, "El nombre debe tener una longitud de 5 a 60 caracteres", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
          Set<String> paises = Locale.getISOCountries(Locale.IsoCountryCode.PART1_ALPHA3);
        
        pPais = PaisTXT.getText();
        if (!paises.contains(pPais)){
             JOptionPane.showMessageDialog(this, "Ese país no existe.", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (5 > pLugar.length() || pLugar.length() > 60){
            JOptionPane.showMessageDialog(this, "El lugar debe tener una longitud de 5 a 60 caracteres", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
          DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
          try {
               pFechainicio = LocalDate.parse(FechainicioTXT.getText(), formatter);
          }
          catch(Exception e){
               JOptionPane.showMessageDialog(this, "El formato de la fecha de inicio es inválido.", 
                    "Error", JOptionPane.ERROR_MESSAGE);
               return;
          }
          try {
               pFechafinal = LocalDate.parse(FechafinalTXT.getText(), formatter);
          }
          catch(Exception e){
               JOptionPane.showMessageDialog(this, "El formato de la fecha final es inválido.", 
                    "Error", JOptionPane.ERROR_MESSAGE);
               return;
          }
          if (pFechainicio.isAfter(pFechafinal)){
               JOptionPane.showMessageDialog(this, "La fecha de inicio no puede ser mayor a la de final.", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
          }
            
            competencia.setNombre(pNombre);
            competencia.setPais(pPais);
            competencia.setLugar(pLugar);
            competencia.setFechainicio(pFechainicio);
            competencia.setFechafinal(pFechafinal);
           
             JOptionPane.showMessageDialog(this, "Se modificó la competencia exitosamente.");  
             
      }//GEN-LAST:event_AceptarButtonActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(ActualizarDatosCompetencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(ActualizarDatosCompetencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(ActualizarDatosCompetencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(ActualizarDatosCompetencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
               public void run() {
                    new ActualizarDatosCompetencia().setVisible(true);
               }
          });
     }

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JButton AceptarButton;
      private javax.swing.JButton CerrarButton;
      private javax.swing.JComboBox<String> ComboCompetencias;
      private javax.swing.JTextField FechafinalTXT;
      private javax.swing.JTextField FechainicioTXT;
      private javax.swing.JTextField LugarTXT;
      private javax.swing.JTextField NombreTXT;
      private javax.swing.JTextField PaisTXT;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLabel jLabel3;
      private javax.swing.JLabel jLabel5;
      private javax.swing.JLabel jLabel6;
      private javax.swing.JLabel jLabel7;
      private javax.swing.JLabel jLabel8;
      // End of variables declaration//GEN-END:variables
}
