/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo.programa1.GUI;

import javax.swing.JOptionPane;
import poo.programa1.Atleta;

/**
 *
 * @author dandi
 */
public class EliminarAtleta extends javax.swing.JFrame {

      /**
       * Creates new form EliminarAtleta
       */
      public EliminarAtleta() {
            initComponents();
            this.setLocationRelativeTo(null);
            FillComboAtletas();
      }

      private void FillComboAtletas(){
            ComboAtletas.removeAllItems();
        Atleta.List.forEach((key, value) -> {
            if (value instanceof Atleta){
                ComboAtletas.addItem(key);
            }
        });
    }
      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            BorrarButton = new javax.swing.JButton();
            CancelarButton = new javax.swing.JButton();
            ComboAtletas = new javax.swing.JComboBox<>();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jLabel1.setText("Eliminar Atleta");

            jLabel2.setText("Atleta");

            BorrarButton.setText("Borrar");
            BorrarButton.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        BorrarButtonActionPerformed(evt);
                  }
            });

            CancelarButton.setText("Cancelar");
            CancelarButton.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        CancelarButtonActionPerformed(evt);
                  }
            });

            ComboAtletas.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        ComboAtletasActionPerformed(evt);
                  }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                              .addGroup(layout.createSequentialGroup()
                                    .addGap(33, 33, 33)
                                    .addComponent(jLabel2)
                                    .addGap(43, 43, 43)
                                    .addComponent(ComboAtletas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                              .addGroup(layout.createSequentialGroup()
                                    .addGap(0, 103, Short.MAX_VALUE)
                                    .addComponent(CancelarButton)
                                    .addGap(63, 63, 63)
                                    .addComponent(BorrarButton)))
                        .addGap(91, 91, 91))
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                          .addComponent(BorrarButton)
                                          .addComponent(CancelarButton))
                                    .addGap(102, 102, 102))
                              .addGroup(layout.createSequentialGroup()
                                    .addComponent(ComboAtletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            );

            pack();
      }// </editor-fold>//GEN-END:initComponents

      private void BorrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarButtonActionPerformed
            // TODO add your handling code here:
            int input = JOptionPane.showConfirmDialog(null, "¿Desea borrar?", "Selecione una opción...",
				JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
            // 0=sí, 1=no,
            if (input == 0){
                  String id = (String) ComboAtletas.getSelectedItem();
                  Atleta atleta = (Atleta) Atleta.List.get(id);
                  Atleta.List.remove(id, atleta);
                  JOptionPane.showMessageDialog(this, "Atleta borrado existosamente.");
            }
            FillComboAtletas();
      }//GEN-LAST:event_BorrarButtonActionPerformed

      private void ComboAtletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboAtletasActionPerformed
            // TODO add your handling code here:
            String id = (String) ComboAtletas.getSelectedItem();
        Atleta atleta = (Atleta) Atleta.List.get(id);
        if (atleta == null){
            return;
        }
        
        
        
      }//GEN-LAST:event_ComboAtletasActionPerformed

      private void CancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarButtonActionPerformed
            // TODO add your handling code here:
            dispose();
            MenuPrincipal menu = new MenuPrincipal();
            menu.setVisible(true);
      }//GEN-LAST:event_CancelarButtonActionPerformed

      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(EliminarAtleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(EliminarAtleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(EliminarAtleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(EliminarAtleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        new EliminarAtleta().setVisible(true);
                  }
            });
      }

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JButton BorrarButton;
      private javax.swing.JButton CancelarButton;
      private javax.swing.JComboBox<String> ComboAtletas;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel2;
      // End of variables declaration//GEN-END:variables
}
